#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-deployment
spec:
  selector:
    matchLabels:
      app: medical-server
  replicas: 1
  template:
    metadata:
      labels:
        app: medical-server
    spec:
      containers:
        - name: medical-container
          #image: gcr.io/tensorflow-serving/resnet
          image: docker.io/joseemanuel/fastapi_medical:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: medical-service
  name: medical-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: medical-server
  type: LoadBalancer
