name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: hello-modelops-world
      run: echo "hello modelops workflow …"
    - name: python version
      run: python --version
    - name: install python requirements
      run: pip install -r requirements.txt
    - name: download dataset
      run: wget -O data/medical-premium.csv ${{github.event.client_payload.dataseturl}}
    - name: cat dataset
      run: cat data/medical-premium.csv

    - name: train model
      run: python model/train.py
    - name: docker build
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .
    - name: docker login
      env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}}

    - name: update docker user in k8 
      run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifest/fastapi.yml

    - name: update model name in k8 
      run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifest/fastapi.yml

    - name: update _ by - 
      run: sed -i 's/_/-/g' manifests/fastapi.yml

    - name: update sha in k8
      run: sed -i 's/{github.sha}/${{github.event.client_payload.sha }}/g' manifest/fastapi.yml

    - name: ls -la 
      run: cat manifest/fastapi.yml
        
    - uses: okteto/context@2.7.0
      with:
        token: ${{secrets.OKTETO_TOKEN }}

    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: manifest/fastapi.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}}


